### ISSUE TITLE
Fails to extract content from Majoras Mask 3D cia/3ds

### ISSUE THREAD

**Issue by Kite2810** [MeltyPlayer/MeltyTool#77]
**Describe the bug**
If launch_ui.bat or rip_majoras_mask_3d.bat is started it says: Dumping ROM C:\Users\Alex\Desktop\Fin Model utility\cli\roms\majoras_mask_3d.3ds...
fin.util.asserts.AssertionException: Failed to extract contents from the ROM: C:\Users\Alex\Desktop\Fin Model utility\cli\roms\majoras_mask_3d.3ds

**Screenshots**

![Image](https://github.com/user-attachments/assets/3bdb02d4-0eed-4e07-bb1d-4aeea79b6007)

![Image](https://github.com/user-attachments/assets/71229d24-6b5e-4342-ab29-5f45e8183b4a)

**Additional context**
I tried different versions. US/EU roms. cci/cia/3ds format. Nothing helped.

**Comment by MeltyPlayer** [comment]
I'm sorry it hasn't been working, thanks for reporting this issue! Can you generate the MD5 hashes for the ROMs you tried so I can find them and try them on my machine?
https://emn178.github.io/online-tools/md5_checksum.html

**Comment by Kite2810** [comment]
Hey :) Yes, here are all hashes:

Legend of Zelda The - Majoras Mask 3D (Europe) (EnFrDeEsIt) (Rev 1) (CIA) -          3df6487969af61127a60dcc07b9c9252
Legend of Zelda The - Majoras Mask 3D (USA) (EnFrEs) (Rev 1) (CIA) -                     742dc4efc2b3b52a3deb4fd086318fb0
Legend of Zelda, The - Majora's Mask 3D (Europe) (En,Fr,De,Es,It) (Rev 1) (3DS) -    4e18a5c0d8d635d7cc069d9a70cb476c
Legend of Zelda, The - Majora's Mask 3D (Europe) (En,Fr,De,Es,It) (3DS) -                e665fff9c5112db7826b5c2fb5f6d953
Legend of Zelda, The - Majora's Mask 3D (USA) (En,Fr,Es) (Rev 1) (3DS) -                 1099761aec53ad863808b0858dec1a0b

**Comment by Readmit0** [comment]
Hi, I'm having the same issue for the same game. I am trying to run it on MM3D and it won't work, I also tested PPMTTYD.

USA v1.0
MD5 hash of majoras_mask_3d.3ds:
48732a0304d5f93b8b78260b225f483f
CertUtil: -hashfile command completed successfully.

USA v1.0
MD5 hash of paper_mario_the_thousand_year_door.iso:
940033540112d9542c4f7db50f638468

**Comment by MeltyPlayer** [comment]
Apologies for the delay! Figured out the issue, it's really foolish on my part.

@Kite2810, in your case, the problem is that the `Fin Model utility` directory has spaces in it. This *shouldn't* cause the logic to break, but there's one spot where I forgot to handle spaces. Thankfully, this should be an easy fix on my end. In the meantime, renaming this directory so it doesn't have spaces should fix the issue on your end. I've confirmed that the `Legend of Zelda, The - Majora's Mask 3D (USA) (En,Fr,Es) (Rev 1) (3DS) - 1099761aec53ad863808b0858dec1a0b` ROM definitely works, but any of the others would probably also work.

@Readmit0, is your case similar? Do you also have spaces in the directory names? If so, please try removing spaces from the path , deleting the `cli/roms/majoras_mask_3d` and `cli/roms/paper_mario_the_thousand_year_door` directories, and rerunning the program. If it still has issues, would you be able to provide the error message you're seeing?

**Comment by spamzilla** [comment]
I wondered if this was the same problem that I was experiencing. I copied my FinModelUtility folder to c:\ and the extraction of Majora's Mask succeeded! It was previewing models as well! I'll be looking into it more soon.

**Comment by Kite2810** [comment]
Don´t be sorry! I should have get it on my own... cuz I had such problems aswell when I make stuff, which is why I use _ a lot. It is working now, thanks!

**Comment by Readmit0** [comment]
> [@Readmit0](https://github.com/Readmit0), is your case similar? Do you also have spaces in the directory names? If so, please try removing spaces from the path , deleting the `cli/roms/majoras_mask_3d` and `cli/roms/paper_mario_the_thousand_year_door` directories, and rerunning the program. If it still has issues, would you be able to provide the error message you're seeing?

Hi, my path doesn't have any spaces. Before it was in my downloads folder, now I put it on the regular c:\ as Spamzilla suggested, but it still doesn't work. These are the paths:

C:\fin_model_utility\roms\majoras_mask_3d.3ds
C:\fin_model_utility\roms\paper_mario_the_thousand_year_door.iso

![Image](https://github.com/user-attachments/assets/aa3e669f-5b89-4177-a20d-c00d9f10b9ed)
